redis.uri = 'redis://localhost'
netty.default.allocator.max-order = 3

[datasources.default]
driverClassName = 'com.mysql.cj.jdbc.Driver'
db-type = 'mysql'

[micronaut.router.static-resources.swagger]
paths = 'classpath:META-INF/swagger'
mapping = '/swagger/**'

[micronaut.router.static-resources.swagger-ui]
paths = 'classpath:META-INF/swagger/views/swagger-ui'
mapping = '/swagger-ui/**'

[micronaut.security]
intercept-url-map = [{access = 'isAnonymous()', pattern = '/swagger/**'}, {access = 'isAnonymous()', pattern = '/swagger-ui/**'}]
authentication = 'session'
token.jwt.signatures.secret.generator.secret = '${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}'
